name: flutter_nfc_reader_example
description: Demonstrates how to use the flutter_nfc_reader plugin.

version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_nfc_reader:
    path: ../

flutter:
  uses-material-design: true
